---

- name: "Include Zabbix gpg ids"
  include_vars: zabbix.yml

- name: "Set short version name"
  set_fact:
    zabbix_short_version: "{{ zabbix_version | regex_replace('\\.', '') }}"

- name: "Debian | Set some facts"
  set_fact:
    apache_log: apache2
    datafiles_path: "/usr/share/zabbix-proxy-{{ zabbix_proxy_database }}"
  when:
    - zabbix_version is version_compare('3.0', '<')
  tags:
    - zabbix-proxt
    - init
    - config

- name: "Debian | Set some facts for Zabbix 3.0"
  set_fact:
    apache_log: apache2
    datafiles_path: "/usr/share/doc/zabbix-proxy-{{ zabbix_proxy_database }}"
  when:
    - zabbix_version is version_compare('3.0', '>=')
  tags:
    - zabbix-proxy
    - init
    - config

- name: "Debian | Install gpg key"
  apt_key:
    id: "{{ sign_keys[zabbix_short_version][ansible_distribution_release]['sign_key'] }}"
    url: http://repo.zabbix.com/zabbix-official-repo.key
  when:
    - zabbix_repo == "zabbix"
  become: yes
  tags:
    - zabbix-proxy
    - init

- name: "Debian | Installing repository {{ ansible_distribution }}"
  apt_repository:
    repo: "{{ item }} http://repo.zabbix.com/zabbix/{{ zabbix_version }}/{{ ansible_distribution.lower() }}/ {{ ansible_distribution_release }} main"
    state: present
  when: zabbix_repo == "zabbix"
  with_items:
    - deb-src
    - deb
  tags:
    - zabbix-proxy
    - init

- name: "Debian | Installing zabbix-proxy-{{ zabbix_proxy_database }}"
  apt:
    pkg: zabbix-proxy-{{ zabbix_proxy_database }}
    update_cache: yes
    cache_valid_time: 3600
    force: yes
    state: present

- name: "Debian | Install Ansible module dependencies"
  apt:
    name: python-psycopg2
    state: present
  when:
    - zabbix_database_creation

- name: "Debian | Install Mysql Client package"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-client
    - python-mysqldb
  when:
    - zabbix_proxy_database == 'mysql'
  tags:
    - zabbix-server
    - init
    - database

- name: "Debian | Install PostgreSQL Client package"
  apt:
    name: postgresql
    state: present
  when:
    - zabbix_proxy_database == 'pgsql'
  tags:
    - zabbix-server
    - init
    - database
