---
# tasks file for dj-wasabi.zabbix-proxy

- name: "Install the correct repository"
  include: "RedHat.yml"
  when: ansible_os_family == "RedHat"

- name: "Install the correct repository"
  include: "Debian.yml"
  when: ansible_os_family == "Debian"

- name: "Installing the database"
  include: "{{ database_type_long }}.yml"

- name: "Create include dir zabbix-proxy"
  file : path={{ proxy_include }}
         owner=zabbix
         group=zabbix
         state=directory

- name: "Create module dir zabbix-proxy"
  file : path={{ proxy_loadmodulepath }}
         owner=zabbix
         group=zabbix
         state=directory

- name: "Configure zabbix-proxy"
  template: src=zabbix_proxy.conf.j2
            dest=/etc/zabbix/zabbix_proxy.conf
            owner=zabbix
            group=zabbix
            mode=644
  notify: zabbix-proxy restarted

- name: "zabbix-proxy started"
  service: name=zabbix-proxy
           state=started
           enabled=yes
